version: 'build_{build}-{branch}'

platform:
  - x64

build:
  parallel: true

configuration:
  - Debug

environment:
  SHELL: "windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "MinGW Makefiles"
      BUILDFLAGS: "VERBOSE=1"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      BUILDFLAGS: "/verbosity:normal"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      BUILDFLAGS: "/verbosity:normal"

init:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - ps: >-
      if (($env:GENERATOR -eq "MinGW Makefiles")) {
        $env:PATH += ";C:\\MinGW\\bin"
      }

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
  - cmake -H.
          -Bbuild
          -G"%GENERATOR%"
          -DCMAKE_BUILD_TYPE="%CONFIGURATION%"
          -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%/install"

build_script:
  - cmake --build build
          --config "%CONFIGURATION%"
          -- %BUILDFLAGS%

after_build:
  - cmake --build build
          --config "%CONFIGURATION%"
          --target install

test_script:
  - cd build
  - ctest --build-config "%CONFIGURATION%"
          --output-on-failure
          --verbose

deploy: off

