version: 'build_{build}-{branch}'

platform: x86

build:
  parallel: true

environment:
  SHELL: "windows"
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "MinGW Makefiles"
      BUILDFLAGS: "VERBOSE=1"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      GENERATOR: "Visual Studio 14 2015"
      BUILDFLAGS: "/verbosity:normal"
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15 2017"
      BUILDFLAGS: "/verbosity:normal"

init:
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - ps: >-
      if (($env:GENERATOR -eq "MinGW Makefiles")) {
        $env:PATH += ";C:\\MinGW\\bin"
      }

build_script:
  - cmake -H. -Bbuild -G"%GENERATOR%"
  - cmake --build build --target install -- %BUILDFLAGS%

test_script:
  - cd build
  - ctest --output-on-failure --verbose

deploy: off

